version: '1'
services:
  postgres:
    image: 'postgres:15.2-alpine'
    container_name: postgres
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_USER=arina
      - POSTGRES_PASSWORD=0000
      - POSTGRES_DB=chinese_course
    restart: always
    networks:
      - backend
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data/

#  liquibase-migrations:
#    image: liquibase/liquibase:4.18
#    depends_on:
#      - postgres
#    command:
#      - --hub-mode=off
#      - --changelog-file=master.xml
#      - --driver=org.postgresql.Driver
#      - --url=jdbc:postgresql://postgres:5432/chinese_course
#      - --username=arina
#      - --password=0000
#      - update
#    volumes:
#      - ./src/main/resources/db/changelog:/liquibase/changelog
#    networks:
#      - backend
#    restart: on-failure

networks:
  backend: {}