server:
  port: ${PORT:8089}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/chinese_course
    username: arina
    password: "0000"
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      springframework: debug
